version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:11.9
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PSQL_TRUST_LOCALNET: "true"
      ENCODING: "UTF8"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
      - shared
networks:
  default:
  shared:
    name: shared
volumes:
  postgres-storage: